</article>
<!-- Main Content -->

<!-- Footer -->
<footer>
	
	<!-- Copyright -->
	<section id="footer-left">
		<p>Copyright &copy; <?php echo date('Y'); ?> Organic Fruit &amp; Veg Ltd. Development by <a href="http://www.cems.uwe.ac.uk/assignments/10008548/" rel="author" target="_blank">10008548</a>.</p>
		<p>Valid <a href="http://validator.w3.org/check?uri=referer" target="_blank" title="HTML 5">HTML</a> &amp; <a href="http://jigsaw.w3.org/css-validator/check/referer" title="CSS 3">CSS</a>.</p>
	</section>
	
</footer>
<!-- Footer -->
</div><!-- Wrapper -->
</body>
</html>