</article>
<footer>
	<section id="footer-left">
		<p>Copyright &copy; Organic Fruit &amp; Veg Ltd. Development by <a href="http://www.cems.uwe.ac.uk/assignments/10008548/" target="_blank">10008548</a>. Valid <a href="http://validator.w3.org/check?uri=referer" target="_blank">HTML</a> &amp; <a href="http://jigsaw.w3.org/css-validator/check/referer" target="_blank">CSS</a>.</p>
	</section>
</footer>
</body>
</html>