</article>
<footer>
	<section id="footer-left">
		<p>Web design by <a href="http://www.cems.uwe.ac.uk/assignments/10008548/" target="_blank">10008548</a>. <a href="http://validator.w3.org/check?uri=referer" target="_blank">Valid HTML</a> | <a href="http://jigsaw.w3.org/css-validator/check/referer" target="_blank">Valid 
CSS</a></p>
	</section>
	<section id="footer-right">
		<p>Insert footer content here</p>
	</section>
</footer>
</body>
</html>